TimeKeeper.Ui/Controllers/DeviationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using TimeKeeper.Data.Models;
using TimeKeeper.Service.Dto;
using TimeKeeper.Service.Services;
using TimeKeeper.Ui.ViewModels;

namespace TimeKeeper.Ui.Controllers
{
    [Authorize]
    public class DeviationsController : Controller
    {
        private readonly ITimeKeeperService _service;
        private readonly UserManager<ApplicationUser> _userManager;

        public DeviationsController(ITimeKeeperService service, UserManager<ApplicationUser> userManager)
        {
            _service = service;
            _userManager = userManager;
        }


        [HttpGet]
        public IActionResult Index(string year, string month, int changeMonth)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            DateTime requestedDate;
            WorkMonthDto workMonth;

            var currentOrganisation = _service.GetCurrentOrganisation(userId);
            var organisationId = currentOrganisation.Id;


            try // Must be refactored
            {
                if (String.IsNullOrEmpty(year) || String.IsNullOrEmpty(month))
                {
                    workMonth = _service.GetLastWorkMonth(userId, organisationId);
                    return View(workMonth);
                }

                requestedDate = DateTime.Parse($"{year}/{month}/01").AddMonths(changeMonth);
                workMonth = _service.GetWorkMonth(userId, organisationId, requestedDate);

                if (workMonth == null)
                {
                    requestedDate = DateTime.Parse($"{year}/{month}/01");
                    workMonth = _service.GetWorkMonth(userId, organisationId, requestedDate);
                }

                return View(workMonth);
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                ViewData["Prompt"] = "Please contact your manager....";
                return View("ErrorPage");
            }
        }


        [HttpGet]
        public IActionResult Add(string year, string month, int monthId)
        {
            var addDeviationViewModel = new DeviationsViewModel() { InputDeviation = new DeviationDto() };

            addDeviationViewModel.InputDeviation.RequestedDate = DateTime.Parse($"{year}/{month}/01");
            var deviationTypes = _service.GetAllDeviationTypes();

            addDeviationViewModel.SelectDaysInMonth = GetAllDaysInMonthAndYear(addDeviationViewModel.InputDeviation.RequestedDate.Year, addDeviationViewModel.InputDeviation.RequestedDate.Month);
            addDeviationViewModel.SelectDeviations = GetDeviationTypesToSelectList(deviationTypes);
            addDeviationViewModel.InputDeviation.WorkMonthId = monthId;

            return View("AddDeviation", addDeviationViewModel);
        }


        [HttpPost]
        public IActionResult Add(DeviationsViewModel addDeviationViewModel)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            addDeviationViewModel.InputDeviation.userId = userId;

            if (ModelState.IsValid)
            {
                try
                {
                    _service.AddDeviation(addDeviationViewModel.InputDeviation);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ViewData["ErrorMessage"] = ex.Message;
                    ViewData["Prompt"] = "Contact your manager.";
                    return View("ErrorPage");
                }
            }

            var deviationTypes = _service.GetAllDeviationTypes();

            addDeviationViewModel.SelectDaysInMonth = GetAllDaysInMonthAndYear(addDeviationViewModel.InputDeviation.RequestedDate.Year, addDeviationViewModel.InputDeviation.RequestedDate.Month);
            addDeviationViewModel.SelectDeviations = GetDeviationTypesToSelectList(deviationTypes);

            return View("AddDeviation", addDeviationViewModel);
        }







        #region None action methods
        private SelectList GetDeviationTypesToSelectList(IEnumerable<DeviationTypeDto> deviationTypes)
        {
            return new SelectList(deviationTypes, "Id", "InfoText");
        }


        private IEnumerable<SelectListItem> GetAllDaysInMonthAndYear(int year, int month)
        {
            var nDays = Enumerable.Range(1, DateTime.DaysInMonth(year, month))
                    .Select(day => new DateTime(year, month, day))
                    .ToList();

            List<SelectListItem> items = new List<SelectListItem>();

            foreach (var d in nDays)
            {
                items.Add(new SelectListItem
                {
                    Value = d.Day.ToString(),
                    Text = d.Date.ToString("d/MM") + " - " + d.DayOfWeek.ToString()
                });
            }

            return items;
        }

        #endregion
    }
}

TimeKeeper.Ui/Controllers/OrganisationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using TimeKeeper.Data.Models;
using TimeKeeper.Service.Dto;
using TimeKeeper.Service.Services;
using TimeKeeper.Ui.ViewModels;

namespace TimeKeeper.Ui.Controllers
{
    [Authorize]
    public class OrganisationsController : Controller
    {

        private readonly ITimeKeeperService _service;
        private readonly UserManager<ApplicationUser> _userManager;

        public OrganisationsController(ITimeKeeperService service, UserManager<ApplicationUser> userManager)
        {
            _service = service;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            IEnumerable<OrganisationDto> organisations;
            OrganisationsViewModel organisationsViewModel = new OrganisationsViewModel(); ;

            try
            {
                organisations = _service.GetOrganisations(userId);
                organisationsViewModel = new OrganisationsViewModel();
                organisationsViewModel.Organisations = organisations;
            }
            catch(Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                ViewData["Prompt"] = "Please contact your manager....";
                return View("ErrorPage");
            }

            return View(organisationsViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            var user = await _userManager.GetUserAsync(User);
            OrganisationDto organisationDto = new OrganisationDto();
            List<OrganisationDto> storedOrganisations = new List<OrganisationDto>();

            
            try
            {
                storedOrganisations = _service.GetOrganisations(user.Id).ToList();
                organisationDto = _service.GetOrganisation(Id);
                storedOrganisations = storedOrganisations.Where(x => x.Id != organisationDto.Id).ToList();
                storedOrganisations.Add(new OrganisationDto { Id = 0, Name = "Set to parent" });
                organisationDto.Id = Id;
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                ViewData["Prompt"] = "Please contact your manager....";
                return View("ErrorPage");
            }

            if (user.Id == organisationDto.OrganisationOwner)
                organisationDto.IsOwner = true;

            ViewBag.Parents = new SelectList(storedOrganisations, "Id", "Name", organisationDto.ParentOrganisationId);

            return View(organisationDto);
        }

        [HttpPost]
        public IActionResult Edit([FromForm] OrganisationDto inputOrganisation)
        {
            try
            {
                _service.UpdateOrganisation(inputOrganisation);
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                ViewData["Prompt"] = "Please contact your manager....";
                return View("ErrorPage");
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Add() // Max nr of org.
        {
            return View("Add");
        }


        [HttpPost]
        public async Task<IActionResult> Add([FromForm] OrganisationDto inputOrganisation)
        {
            var user = await _userManager.GetUserAsync(User);

            try
            {
                _service.AddOrganisation(inputOrganisation.Name, user);
            }
            catch(Exception ex)
            {
                TempData["Error"] = ex.Message;
                return View();
            }

            return RedirectToAction("Index");
        }
    }
}

TimeKeeper.Ui/Views/Shared/ErrorPage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@ViewData["ErrorMessage"] <br/>
@ViewData["Prompt"]

TimeKeeper.Ui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TimeKeeper.Ui</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Deviations" asp-action="Index">TimeKeeper.Ui</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_ManagerPartial" />
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Deviations" asp-action="Index">MyTime</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TimeKeeper.Ui - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TimeKeeper.Ui/Views/Shared/_ManagerPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<TimeKeeper.Data.Models.ApplicationUser> SignInManager
@inject UserManager<TimeKeeper.Data.Models.ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    var signedInUser = UserManager.GetUserAsync(User).Result;
    if (signedInUser.MaximumNumberOfOrganisations > 0)
    {
        <a class="nav-link text-dark" asp-area="" asp-controller="Organisations" asp-action="Index">Manage Organisations</a>
    }
}